* TODO

* Notes about the simulation
  per grid, there should generally be only one particle per grid at the rest state
  they should be pushing away from each other, so why do they clump?

** Clustering - don't even get that yet
   Clumping is a common bug that most people have, that has to do with the choice of kernel, the piecewise function should deal with it
   Clustering is also solved by having two kernel functions that are used, with one being the near case? - It just means that the kernels are different for each measurement

** Data structure\
   Currently the hash being used right now doesn't correctly index the grid space to get the correct spaces
   Look into switching to openvdb <-- designed exactly for this kind of thing
   
** Adding energy  
   Right now, for some reason, energy is being added into the system per collision?
   Perhaps that has to do with the pressure equation?
   recalculating mass probably needs to happen as well
   [[https://github.com/rlguy/SPHFluidSim/blob/master/src/sphfluidsimulation.cpp][this guy]] chose to limit the maximum acceleration that could occur
   I AM DOING THIS AS WELL, NOT A GOOD IDEA AT ALL
** Constant Mass
   In order for mass to be conserved in the simulation, we don't mess with the mass of each particle
** Viscosity should be added

** Influence circle
   there seems to be a problem with particles being affected by particles to the side of it (perhaps the viscosity term will help)
